---
- name: Fail if not running on a RHEL host
  fail:
  when: ansible_distribution != "RedHat"

- name: Install required packages
  package:
    name: "{{ sync_required_packages }}"
    state: present

- name: Ensure required repositories are enabled
  command: "yum-config-manager --enable {{ base_repos + extra_repos | join(' --enable ') }}"

- name: Download specified repositories
  command: reposync {{ reposync_opts }} --repoid={{ item }} --download_path={{ download_cache_dir }}
  with_items: {{ base_repos + extra_repos }}

- name: Generate repo metadata
  shell: createrepo {{ download_cache_dir }}/{{ item }} --update -g comps.xml || createrepo {{ download_cache_dir }}/{{ item }} --update
  with_items: {{ base_repos + extra_repos }}

- name: Push repos to nexus
  shell: find . -type f | xargs -I {} -P{{ upload_parallel_count }} curl -u {{ nexus_user }}:{{ nexus_password }} --upload-file {} http://{{ nexus_host }}/repository/$repo/{}
  args:
    warn: no
    chdir: "{{ download_cache_dir }}/{{ item }}"
  with_items: {{ base_repos + extra_repos }}
