---
- name: Fail if not running on a RHEL host
  fail:
  when: ansible_distribution != "RedHat"

- name: Set yum package excludes
  lineinfile:
    path: /etc/yum.conf
    regexp: '^exclude='
    line: "exclude={{ yum_excludes }}"
 
- name: Install required packages
  package:
    name: "{{ sync_required_packages }}"
    state: present

- name: Disable all rhsm repos
  command: "subscription-manager config --rhsm.manage_repos=0"

- name: Add repos from nexus
  yum_repository:
     name: "nexus-{{ item }}"
     description: "nexus mirror repo for {{ item }}"
     baseurl: "{{ nexus_host }}/repository/{{ item }}"
     gpgcheck: no
  with_items: "{{ base_repos + extra_repos }}"

- name: Download repos from nexus
  command: reposync {{ reposync_opts }} --norepopath --repoid=nexus-{{ item }} --download_path={{ download_cache_dir }}/{{ item }}
  with_items: "{{ base_repos + extra_repos }}"
  ignore_errors: yes

- name: Disable repos from nexus
  yum_repository:
     name: "nexus-{{ item }}"
     description: "nexus mirror repo for {{ item }}"
     baseurl: "{{ nexus_host }}/repository/{{ item }}"
     gpgcheck: no
     state: absent
  with_items: "{{ base_repos + extra_repos }}"

- name: Enable rhsm repos
  command: "subscription-manager config --rhsm.manage_repos=1"

- name: Ensure required RH repositories are enabled
  command: "yum-config-manager --enable {{ (base_repos + extra_repos) | join(' --enable ') }}"

- name: Download specified repositories
  command: reposync {{ reposync_opts }} --repoid={{ item }} --download_path={{ download_cache_dir }}
  with_items: "{{ base_repos + extra_repos }}"

- name: Generate repo metadata
  shell: createrepo {{ download_cache_dir }}/{{ item }} --update -g comps.xml || createrepo {{ download_cache_dir }}/{{ item }} --update
  with_items: "{{ base_repos + extra_repos }}"

- name: Push repos to nexus
  shell: find . -type f | xargs -I {} -P{{ upload_parallel_count }} curl -u {{ nexus_user }}:{{ nexus_password }} --upload-file {} {{ nexus_host }}/repository/{{ item }}/{}
  args:
    warn: no
    chdir: "{{ download_cache_dir }}/{{ item }}"
  with_items: "{{ base_repos + extra_repos }}"
