---
- name: authenticate to gerrit
  include_role:
    name: gerrit-prepare-urllib

- name: check if zuul user exists
  uri:
    url: "http://{{ gerrit_host }}/accounts/zuul"
    status_code: 200, 404
    headers:
      Cookie: "{{ gerrit_cookies }}"
  register: zuul_user_check

- name: create zuul gerrit account
  uri:
    url: "http://{{ gerrit_host }}/accounts/zuul"
    method: PUT
    status_code: 201
    body_format: json
    body:
      name: zuul
      ssh_key: "{{ lookup('file', '{{ gerrit_ssh_keys }}/zuul_rsa.pub') }}"
      groups:
        - "Non-Interactive Users"
    headers:
      Cookie: "{{ gerrit_cookies }}"
      x-gerrit-auth: "{{ gerrit_auth }}"
  when:
    - zuul_user_check.status == 404 or (gerrit_force_create_zuul_user | default(false))

- name: add zuul SSH key to gerrit
  uri:
    url: "http://{{ gerrit_host }}/accounts/zuul/sshkeys"
    method: POST
    body: "{{ lookup('file', '{{ gerrit_ssh_keys }}/zuul_rsa.pub') }}"
    status_code: 201
    headers:
      Content-Type: text/plain
      Cookie: "{{ gerrit_cookies }}"
      x-gerrit-auth: "{{ gerrit_auth }}"
