---
- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0755
  with_items:
    - /opt/zuul-logserver/
    - /home/zuul/.ssh

# for now log server is placed somewhere and accessed from executor with zuul user
- name: create logserver data directory
  file:
    path: "{{ logserver_data_directory }}"
    state: directory
    recurse: yes
    mode: 0775

- name: extract static content for ARA reports
  unarchive:
    src: static.tgz
    dest: "{{ logserver_data_directory }}"

- name: "collect {{ gerrit_ssh_keys }}/logserver_rsa.pub' ssh key"
  set_fact:
    logserver_pubkey: "{{ lookup('file', '{{ gerrit_ssh_keys }}/logserver_rsa.pub') }}"

- name: add logserver public ssh key to zuul's authorized_keys
  shell: "echo {{ logserver_pubkey }} >> /home/zuul/.ssh/authorized_keys"

- name: fix /home/zuul/.ssh/authorized_keys security
  file:
    path: /home/zuul/.ssh/authorized_keys
    mode: 0644

- name: copy logserver configuration files
  copy:
    src: "httpd.conf"
    dest: "/opt/zuul-logserver/httpd.conf"
    force: true

- name: apply logserver compose file
  template:
    src: docker-compose.yaml.j2
    dest: /opt/zuul-logserver/docker-compose.yaml
    mode: 0644

- name: start logserver
  docker_service:
    project_src: /opt/zuul-logserver/

- name: logserver log rotate task
  template:
    src: zuul-log-rotate.j2
    dest: /etc/cron.daily/zuul-log-rotate
    mode: 0755
