---

# project must have 'src' property with name
# project may have 'src_org' key - by default it's 'Juniper'. after moving the project it must have new src_org 
# for moving project it must have 'dst' and 'dst_org' keys
# for projects with specific branches they can be specified as a list under 'branches' key

default_branches:
  - "master"
projects:
  - {src: "contrail", dst_org: "tungstenfabric", dst: "atom"}
  - {src: "contrail-analytics", dst_org: "tungstenfabric", dst: "tf-analytics"}
  - {src: "contrail-ansible-deployer", dst_org: "tungstenfabric", dst: "tf-ansible-deployer"}
  - {src: "contrail-api-client", dst_org: "tungstenfabric", dst: "tf-api-client"}
  - {src: "contrail-build", dst_org: "tungstenfabric", dst: "tf-build"}
  - {src: "contrail-common", dst_org: "tungstenfabric", dst: "tf-common"}
  - {src: "contrail-container-builder", dst_org: "tungstenfabric", dst: "tf-container-builder"}
  - {src: "contrail-controller", dst_org: "tungstenfabric", dst: "tf-controller"}
  - {src: "contrail-deployers-containers", dst_org: "tungstenfabric", dst: "tf-deployers-containers"}
  - {src: "contrail-docs", dst_org: "tungstenfabric", dst: "tf-docs"}
  - {src: "contrail-dpdk", dst_org: "tungstenfabric", dst: "tf-dpdk",
     branches: ["contrail_dpdk_17_02", "contrail_dpdk_17_11_3", "contrail_dpdk_18_05_1"]}
  - {src: "contrail-fabric-utils", dst_org: "tungstenfabric", dst: "tf-fabric-utils"}
  - {src: "contrail-heat", dst_org: "tungstenfabric", dst: "tf-heat-plugin"}
  - {src: "contrail-java-api", dst_org: "tungstenfabric", dst: "tf-java-api"}
  - {src: "contrail-kolla-ansible", dst_org: "tungstenfabric", dst: "kolla-ansible",
     branches: ["contrail/ocata", "contrail/queens", "contrail/rocky"]}
  - {src: "contrail-neutron-plugin", dst_org: "tungstenfabric", dst: "tf-neutron-plugin"}
  - {src: "contrail-nova-vif-driver", dst_org: "tungstenfabric", dst: "tf-nova-vif-driver"}
  - {src: "contrail-packages", dst_org: "tungstenfabric", dst: "tf-packages"}
  - {src: "contrail-project-config", dst_org: "tungstenfabric-infra", dst: "project-config",
     branches: ["master"],
     excludes: ['zuul/main.yaml', 'zuul.d/projects.yaml']}
  - {src: "contrail-specs", dst_org: "tungstenfabric", dst: "tf-specs"}
  - {src: "contrail-test", dst_org: "tungstenfabric", dst: "tf-test"}
  - {src: "contrail-third-party", dst_org: "tungstenfabric", dst: "tf-third-party"}
  - {src: "contrail-third-party-cache", dst_org: "tungstenfabric", dst: "tf-third-party-cache"}
  - {src: "contrail-third-party-packages", dst_org: "tungstenfabric", dst: "tf-third-party-packages"}
  - {src: "contrail-tripleo-heat-templates", dst_org: "tungstenfabric", dst: "tf-tripleo-heat-templates",
     branches: ["master", "stable/newton", "stable/queens", "stable/rocky", "stable/stein"]}
  - {src: "contrail-tripleo-puppet", dst_org: "tungstenfabric", dst: "tf-tripleo-puppet",
     branches: ["master", "stable/newton", "stable/queens", "stable/rocky", "stable/stein"]}
  - {src: "contrail-vcenter-manager", dst_org: "tungstenfabric", dst: "tf-vcenter-manager"}
  - {src: "contrail-vcenter-fabric-manager", dst_org: "tungstenfabric", dst: "tf-vcenter-fabric-manager"}
  - {src: "contrail-vcenter-plugin", dst_org: "tungstenfabric", dst: "tf-vcenter-plugin"}
  - {src: "contrail-vnc", dst_org: "tungstenfabric", dst: "tf-vnc"}
  - {src: "contrail-vro-plugin", dst_org: "tungstenfabric", dst: "tf-vro-plugin"}
  - {src: "contrail-vrouter", dst_org: "tungstenfabric", dst: "tf-vrouter"}
  - {src: "contrail-vrouter-java-api", dst_org: "tungstenfabric", dst: "tf-vrouter-java-api"}
  - {src: "contrail-zuul-jobs", dst_org: "tungstenfabric-infra", dst: "tungsten-zuul-jobs",
     branches: ["master"]}
  - {src: "contrail-web-controller", dst_org: "tungstenfabric", dst: "tf-web-controller"}
  - {src: "contrail-web-core", dst_org: "tungstenfabric", dst: "tf-web-core"}
  - {src: "contrail-webui-third-party", dst_org: "tungstenfabric", dst: "tf-webui-third-party"}
  - {src: "openshift-ansible", dst_org: "tungstenfabric", dst: "openshift-ansible",
     branches: ["release-3.11", "release-3.11-contrail"]}
  - {src: "vijava", dst_org: "tungstenfabric", dst: "vijava"}
