---

# project must have 'src' property with name
# project may have 'src_org' key - by default it's 'Juniper'. after moving the project it must have new src_org 
# for moving project it must have 'dst' and 'dst_org' keys
# for projects with specific branches they can be specified as a list under 'branches' key

default_branches:
  - "master"
  - "R1909"
projects:
  - {src: "contrail-analytics", dst_org: "tungstenfabric", dst: "analytics"}
  - {src: "contrail-project-config", dst_org: "tungstenfabric-infra", dst: "project-config",
     branches: ["master"],
     excludes: ['zuul/main.yaml', 'zuul.d/projects.yaml']}

  # repos in doc that are not used in the project. let's move them separately if needed
  #- {src: "horizon", dst_org: "tungstenfabric", dst: "openstack-horizon"}
  #- {src: "nova", dst_org: "tungstenfabric", dst: "openstack-nova"}
  #- {src: "contrail-generateDS", dst_org: "tungstenfabric", dst: "generateDS"}

  # next repos was not found in review.opencontrail.org
  #- {src: "zuul-jobs", dst_org: "tungstenfabric-infra", dst: "zuul-jobs"}
  #- {src: "contrail-publisher", dst_org: "tungstenfabric-infra", dst: "docker-publisher"}
