---

# project must have 'src' property with name
# project may have 'src_org' key - by default it's 'Juniper'. after moving the project it must have new src_org 
# for moving project it must have 'dst' and 'dst_org' keys
# for projects with specific branches they can be specified as a list under 'branches' key

default_branches:
  - "master"
projects:
  - {src: "contrail-project-config",
     branches: ["master"],
     excludes: ['zuul/main.yaml', 'zuul.d/projects.yaml', 'zuul.d/jobs.yaml']}
  - {src: "contrail-zuul-jobs",
     branches: ["master"],
     excludes: ['zuul.d/base-jobs.yaml']}
  - {src: "contrail-dpdk", dst_org: "tungstenfabric", dst: "tf-dpdk",
     branches: ["contrail_dpdk_17_02", "contrail_dpdk_17_11_3", "contrail_dpdk_18_05_1"]}
  - {src: "contrail", dst_org: "tungstenfabric", dst: "atom"}

  - {src: "contrail-controller", dst_org: "tungstenfabric", dst: "tf-controller"}

  - {src: "tf-analytics", src_org: "tungstenfabric"}
  - {src: "tf-ansible-deployer", src_org: "tungstenfabric"}
  - {src: "tf-api-client", src_org: "tungstenfabric"}
  - {src: "tf-build", src_org: "tungstenfabric"}
  - {src: "tf-common", src_org: "tungstenfabric"}
  - {src: "tf-container-builder", src_org: "tungstenfabric"}
  - {src: "tf-deployers-containers", src_org: "tungstenfabric"}
  - {src: "tf-fabric-utils", src_org: "tungstenfabric"}
  - {src: "tf-heat-plugin", src_org: "tungstenfabric"}
  - {src: "tf-helm-deployer", src_org: "tungstenfabric"}
  - {src: "tf-java-api", src_org: "tungstenfabric"}
  - {src: "tf-kolla-ansible", src_org: "tungstenfabric",
     branches: ["contrail/ocata", "contrail/queens", "contrail/rocky", "contrail/train"]}
  - {src: "tf-neutron-plugin", src_org: "tungstenfabric"}
  - {src: "tf-nova-vif-driver", src_org: "tungstenfabric"}
  - {src: "tf-old-docs", src_org: "tungstenfabric"}
  - {src: "tf-openshift-ansible", src_org: "tungstenfabric",
     branches: ["master", "release-3.11-contrail"]}
  - {src: "tf-specs", src_org: "tungstenfabric"}
  - {src: "tf-packages", src_org: "tungstenfabric"}
  - {src: "tf-test", src_org: "tungstenfabric"}
  - {src: "tf-third-party", src_org: "tungstenfabric"}
#  - {src: "tf-third-party-cache", src_org: "tungstenfabric"}
  - {src: "tf-third-party-packages", src_org: "tungstenfabric"}
  - {src: "tf-tripleo-heat-templates", src_org: "tungstenfabric",
     branches: ["stable/queens", "stable/train"]}
  - {src: "tf-tripleo-puppet", src_org: "tungstenfabric",
     branches: ["master", "stable/newton", "stable/queens", "stable/rocky", "stable/stein"]}
  - {src: "tf-vcenter-fabric-manager", src_org: "tungstenfabric"}
  - {src: "tf-vcenter-manager", src_org: "tungstenfabric"}
  - {src: "tf-vcenter-plugin", src_org: "tungstenfabric"}
  - {src: "tf-vijava", src_org: "tungstenfabric"}
  - {src: "tf-vnc", src_org: "tungstenfabric"}
  - {src: "tf-vro-plugin", src_org: "tungstenfabric"}
  - {src: "tf-vrouter", src_org: "tungstenfabric"}
  - {src: "tf-vrouter-java-api", src_org: "tungstenfabric"}
  - {src: "tf-web-controller", src_org: "tungstenfabric"}
  - {src: "tf-web-core", src_org: "tungstenfabric"}
  - {src: "tf-webui-third-party", src_org: "tungstenfabric"}
