---

default_branches:
  - "master"
projects:
  - {src: "contrail-analytics", dst_org: "tungstenfabric", dst: "analytics"}
  - {src: "contrail-api-client", dst_org: "tungstenfabric", dst: "api-client"}
  - {src: "contrail-build", dst_org: "tungstenfabric-tools", dst: "build"}
  - {src: "contrail-common", dst_org: "tungstenfabric", dst: "common"}
  - {src: "contrail-controller", dst_org: "tungstenfabric", dst: "controller"}
  - {src: "contrail-project-config", dst_org: "tungstenfabric-infra", dst: "project-config"}
  - {src: "contrail-provisioning", dst_org: "tungstenfabric-tools", dst: "provisioning"}
  - {src: "contrail-sandesh", dst_org: "tungstenfabric", dst: "sandesh"}
  - {src: "contrail-specs", dst_org: "tungstenfabric", dst: "specs"}
  - {src: "contrail-vnc", dst_org: "tungstenfabric", dst: "vnc"}
  - {src: "contrail-zuul-jobs", dst_org: "tungstenfabric-infra", dst: "tungsten-zuul-jobs"}
