---
- name: install pre-requisites
  package:
    name: ['git', 'git-review']

- name: make sure a service is running
  systemd:
    name: docker.service
    state: started
    enabled: yes
    
- name: copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
  with_items:
    - {src: "./", dest: "/opt/zuul/"}
    - {src: "{{ gerrit_ssh_keys }}/", dest: "/opt/zuul/ssh_keys"}

- name: protect private keys (admin)
  file:
    path: /opt/zuul/ssh_keys/admin_rsa
    mode: 0600

- name: protect private keys (zuul)
  file:
    path: /opt/zuul/ssh_keys/zuul_rsa
    mode: 0600

- name: protect private keys (nodepool)
  file:
    path: /opt/zuul/ssh_keys/nodepool_rsa
    mode: 0600

- name: create /var/lib/zuul/build directory
  file:
    path: /var/lib/zuul/builds
    state: directory
    recurse: yes

- name: create /var/lib/zuul/git directory
  file:
    path: /var/lib/zuul/git
    state: directory

- name: create /var/lib/zuul/ssh directory
  file:
    path: /var/lib/zuul/ssh
    state: directory

- set_fact:
    zuul_config_project: "Juniper/contrail-project-config"
    zuul_zuul_jobs_project: "Juniper/contrail-zuul-jobs"
    zuul_third_party_packages: "Juniper/contrail-third-party-packages"

- name: setup zuul config project
  set_fact:
    zuul_config_project: "Juniper/tf-ci-config-docker"
    zuul_zuul_jobs_project: "Juniper/tf-ci-zuul-jobs-docker"
    zuul_third_party_packages: "Juniper/tf-third-party-packages"
  when:
    - zuul_build_with_docker is defined
    - zuul_build_with_docker == true

- name: trace zuul config project
  debug:
    msg: |
      zuul_config_project: {{ zuul_config_project }}
      zuul_zuul_jobs_project: {{ zuul_zuul_jobs_project }}
      zuul_third_party_packages: {{ zuul_third_party_packages }}

- name: apply zuul configuration
  template:
    src: "{{ item }}.j2"
    dest: "/opt/zuul/etc_zuul/{{ item }}"
  with_items:
    - zuul.conf
    - main.yaml

- name: create /opt/zuul/.ssh directory
  file:
    path: /opt/zuul/.ssh
    state: directory

- name: construct known_hosts for gerrit
  shell: "ssh-keyscan -p {{ item.port }} -t ecdsa {{ item.host }} >> /opt/zuul/.ssh/known_hosts"
  with_items:
    - {host: "{{ gerrit_host }}", port: 22}
    - {host: "{{ gerrit_host }}", port: 29418}

- name: apply docker-compose.yaml
  template:
    src: docker-compose.yaml.j2
    dest: /opt/zuul/docker-compose.yaml

- name: start zuul service
  docker_service:
    project_src: /opt/zuul/
