---
- name: install pre-requisites
  package:
    name: ['git', 'git-review']

- name: make sure a service is running
  systemd:
    name: docker.service
    state: started
    enabled: yes

- name: Ensure zuul user exists
  user:
    name: "zuul"
    state: present
    groups: docker
    append: yes

- name: copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
  with_items:
    - {src: "./", dest: "/opt/zuul/"}
    - {src: "{{ gerrit_ssh_keys }}/", dest: "/opt/zuul/ssh_keys"}

- name: protect SSH private keys
  file:
    path: /opt/zuul/ssh_keys/{{ item }}_rsa
    mode: 0600
  with_items:
    - admin
    - zuul
    - nodepool

- name: create /var/lib/zuul/ directories
  file:
    path: /var/lib/zuul/{{ item }}
    state: directory
    recurse: yes
  with_items:
    - build
    - git
    - ssh

- set_fact:
    zuul_config_project: "Juniper/contrail-project-config"
    zuul_zuul_jobs_project: "Juniper/contrail-zuul-jobs"
    zuul_third_party_packages: "Juniper/contrail-third-party-packages"

- name: setup zuul config project
  set_fact:
    zuul_config_project: "Juniper/tf-ci-config-docker"
    zuul_zuul_jobs_project: "Juniper/tf-ci-zuul-jobs-docker"
    zuul_third_party_packages: "Juniper/tf-third-party-packages"
  when:
    - zuul_build_with_docker is defined
    - zuul_build_with_docker == true

- name: trace zuul config project
  debug:
    msg: |
      zuul_config_project: {{ zuul_config_project }}
      zuul_zuul_jobs_project: {{ zuul_zuul_jobs_project }}
      zuul_third_party_packages: {{ zuul_third_party_packages }}

- name: apply zuul configuration
  template:
    src: "{{ item }}.j2"
    dest: "/opt/zuul/etc_zuul/{{ item }}"
  with_items:
    - zuul.conf
    - main.yaml

- name: create /opt/zuul/.ssh directory
  file:
    path: /opt/zuul/.ssh
    state: directory

- name: construct known_hosts for gerrit
  shell: "ssh-keyscan -p {{ item.port }} -t ecdsa {{ item.host }} >> /opt/zuul/.ssh/known_hosts"
  with_items:
    - {host: "{{ gerrit_host }}", port: 22}
    - {host: "{{ gerrit_host }}", port: 29418}

- name: construct authorized_keys for zuul
  shell: "cat /opt/zuul/ssh_keys/{{ item }}_rsa.pub >> /opt/zuul/.ssh/authorized_keys"
  with_items:
    - nodepool

- name: apply docker-compose.yaml
  template:
    src: docker-compose.yaml.j2
    dest: /opt/zuul/docker-compose.yaml

- name: start zuul service
  docker_service:
    project_src: /opt/zuul/
