---
- name: install pre-requisites
  package:
    name: ['git', 'git-review']

- name: make sure a service is running
  systemd:
    name: docker.service
    state: started
    enabled: yes
    
- name: copy config files
  copy:
    src: ./
    dest: /opt/zuul/

- name: protect private keys (admin)
  file:
    path: /opt/zuul/ssh_keys/admin
    mode: 0600

- name: protect private keys (zuul)
  file:
    path: /opt/zuul/ssh_keys/zuul
    mode: 0600

- name: protect private keys (nodepool)
  file:
    path: /opt/zuul/ssh_keys/nodepool
    mode: 0600

- name: create /var/lib/zuul/build directory
  file:
    path: /var/lib/zuul/builds
    state: directory
    recurse: yes

- name: create /var/lib/zuul/git directory
  file:
    path: /var/lib/zuul/git
    state: directory

#- name: up
#  docker_service:
#    project_src: /opt/zuul/
