sync_required_packages:
  - yum-utils
  - createrepo

base_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-optional-rpms
extra_repos:
  - rhel-7-server-openstack-13-devtools-rpms
  - rhel-7-server-openstack-13-rpms
  - rhel-7-server-openstack-13-tools-rpms
  - rhel-server-rhscl-7-rpms

download_cache_dir: ~/repos
reposync_opts: "--newest-only --gpgcheck -l --downloadcomps --download-metadata"

nexus_host: http://pnexus.sytes.net/
nexus_user: admin
# nexus_password: passwordgoeshere

repo_prefix: "repository/"
upload_parallel_count: 8
