---
- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0755
  with_items:
    - /opt/nodepool-launcher/etc_nodepool
    - /opt/nodepool-launcher/.ssh
    - /opt/nodepool/images
    - /var/log/zuul

- name: copy ssh keys
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    mode: 0644
  with_items:
    - {src: "./", dest: "/opt/nodepool-launcher"}
    - {src: "{{ gerrit_ssh_keys }}/", dest: "/opt/nodepool-launcher/ssh_keys"}

- name: protect SSH private keys
  file:
    path: /opt/nodepool-launcher/ssh_keys/{{ item }}_rsa
    mode: 0600
  with_items:
    - admin
    - zuul
    - nodepool

- name: construct known_hosts for gerrit
  shell: "ssh-keyscan -p {{ item.port }} -t ecdsa {{ item.host }} >> /opt/nodepool-launcher/.ssh/known_hosts"
  with_items:
    - {host: "{{ gerrit_host }}", port: 22}
    - {host: "{{ gerrit_host }}", port: 29418}

- name: "clone {{ zuul_config_project }}"
  git:
    repo: "ssh://zuul@{{ gerrit_host }}:29418/{{ zuul_config_project }}"
    dest: /opt/nodepool-launcher/config
    accept_hostkey: yes
    force: true
    key_file: /opt/nodepool-launcher/ssh_keys/zuul_rsa

- name: copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    mode: 0644
  with_items:
    - {src: "./", dest: "/opt/nodepool-launcher"}

- name: start nodepool-launcher service
  docker_service:
    project_src: /opt/nodepool-launcher/
