all:
  children:
    gerrit:
      hosts:
        192.168.56.103:
      vars:
        gerrit_baseurl: "http://192.168.56.103/"
        gerrit_oauth_client_id: cbb0e2c7098bdbdde3c3
        gerrit_oauth_client_secret: a4356301e414066d94ddd353c04a1e706ae75641
    nexus:
      hosts:
        192.168.56.103:
    quickstart:
      hosts:
        13.53.206.7
      vars:
        gerrit_host: 13.53.158.75
        gerrit_port: 8080
#        ansible_python_interpreter: /usr/bin/python3
