all:
  children:
    gerrit:
      hosts:
        13.53.140.16:
    nexus:
      hosts:
        192.168.56.103:
    quickstart:
      hosts:
        13.53.136.92:
      vars:
        remote_user: ubuntu
        gerrit_url: http://13.53.140.16:80
        gerrit_sshd_host: 13.53.140.16
        gerrit_sshd_port: 29418
#        ansible_python_interpreter: /usr/bin/python3
