all:
  vars:
      gerrit_url: "http://192.168.56.101"
      gerrit_ssh_keys: "{{ lookup('env', 'HOME') }}/gerrit/ssh"
      gerrit_ssh_keys_generate: false
      gerrit_create_zuul_user: true
  children:
    centos7-docker-builder:
      hosts:
        13.48.6.67:
      vars:
        remote_user: centos
    gerrit:
      hosts:
        192.168.56.101:
      vars:
        remote_user: ubuntu
        gerrit_oauth_client_id: cbb0e2c7098bdbdde3c3
        gerrit_oauth_client_secret: a4356301e414066d94ddd353c04a1e706ae75641
        gerrit_front_port: 80
        force_update_repos: true
    nexus:
      hosts:
        13.53.186.64:
      vars:
        remote_user: ubuntu
    zuul:
      hosts:
        zuul-test.ddns.net:
      vars:
        remote_user: ubuntu
        zuul_front_port: 8080
        zuul_logs_port: 8123
    init:
      hosts:
        zuul-test.ddns.net:
          remote_user: ubuntu
