all:
  vars:
      gerrit_url: "http://192.168.56.101"
  children:
    centos7-docker-builder:
      hosts:
        13.48.6.67:
      vars:
        remote_user: centos
    gerrit:
      hosts:
        192.168.56.101:
      vars:
        remote_user: ubuntu
        gerrit_oauth_client_id: cbb0e2c7098bdbdde3c3
        gerrit_oauth_client_secret: a4356301e414066d94ddd353c04a1e706ae75641
        force_update_repos: true
    nexus:
      hosts:
        13.53.186.64:
      vars:
        remote_user: ubuntu
    zuul:
      hosts:
        192.168.56.101:
      vars:
        remote_user: ubuntu
        gerrit_sshd_host: gerrit-test.ddns.net
        gerrit_sshd_port: 29418
        gerrit_zuul_password: "secret"
    init:
      hosts:
        zuul-test.ddns.net:
          remote_user: ubuntu
