all:
  children:
    gerrit:
      hosts:
        192.168.56.103:
    nexus:
      hosts:
        192.168.56.103:
    quickstart:
      hosts:
        13.53.206.7
      vars:
        gerrit_host: 13.53.158.75
        gerrit_port: 8080
#        ansible_python_interpreter: /usr/bin/python3
