all:
  children:
    gerrit:
      hosts:
        13.53.192.123:
      vars:
        remote_user: ubuntu
        gerrit_baseurl: "http://13.53.192.123/"
    nexus:
      hosts:
        192.168.56.103:
    quickstart:
      hosts:
        13.48.3.11:
      vars:
        remote_user: ubuntu
        gerrit_url: http://13.53.192.123:80
        gerrit_http_scheme: http
        gerrit_http_host: 13.53.192.123
        gerrit_http_port: 80
        gerrit_sshd_host: 13.53.192.123
        gerrit_sshd_port: 29418
    zuul:
      hosts:
        zuul-test.ddns.net:
      vars:
        remote_user: ubuntu
        gerrit_url: http://gerrit-test.ddns.net
        gerrit_http_scheme: http
        gerrit_http_host: gerrit-test.ddns.net
        gerrit_http_port: 80
        gerrit_sshd_host: gerrit-test.ddns.net
        gerrit_sshd_port: 29418
    init:
      hosts:
        zuul-test.ddns.net:
          remote_user: ubuntu
