# Version 2 is the latest that is supported by docker-compose in
# Ubuntu Xenial.
version: '2'

services:
  builder:
    command: "nodepool-builder -d -l /etc/nodepool/builder-logging.conf"
    image: progmaticlab/nodepool-builder:0.5.1
    environment:
      ZUUL_USER_SSH_PUBLIC_KEY: /var/ssh/nodepool_rsa.pub
      OS_CLIENT_CONFIG_FILE: /etc/cloud/cloud.yaml
    # to be able to mount loop devices
    privileged: true
    # to avoid strange MTU issue
    network_mode: host
    volumes:
      - "./config/nodepool:/etc/nodepool"
      - "/etc/cloud/cloud.yaml:/etc/cloud/cloud.yaml:ro"
      - "/var/log/zuul:/var/log/nodepool"
      - "./ssh_keys:/var/ssh"
      - "./.ssh:/root/.ssh"
      - "/opt/nodepool/images:/opt/nodepool_dib"
      - "/var/run:/var/run"
      - "/lib/modules:/lib/modules"
      - "/bin/systemctl:/bin/systemctl"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
