---
- name: install ntp packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - ntpdate
    - ntp

- name: set ntp service name
  set_fact:
    ntp_svc_name: "{{ 'ntp' if ansible_os_family == 'Debian' else 'ntpd' }}"

- name: start ntp service
  service: name={{ ntp_svc_name }} state=started enabled=yes

# we need to remove python-requests installed by distutils
# cause it conflicts with requests lib installed by pip during docker-compose install
- name: remove python-requests installed by distutils
  package:
    name: python-requests
    state: absent
  register: res
  retries: 5
  until: res | success

- include: "{{ ansible_os_family }}.yml"

- name: start docker daemon
  include: "start_docker_{{ ansible_system }}.yml"

- name: add live-restore option
  include: "live_restore_{{ ansible_system }}.yml

- name: install python compose
  pip:
    name: docker-compose
