# Version 2 is the latest that is supported by docker-compose in
# Ubuntu Xenial.
version: '2'

services:
  launcher:
    command: "nodepool-builder -d"
    image: progmaticlab/nodepool-builder:0.5.1
    pid: host
    ipc: host
    volumes:
      - "./etc_nodepool:/etc/nodepool"
      - "/var/log/zuul:/var/log/zuul"
      - "/var/run:/var/run"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
