---
- name: configure docker host tcp connection on port {{ node_docker_port }}
  replace:
    path: /usr/lib/systemd/system/docker.service
    regexp: "^ExecStart=.*"
    replace: "ExecStart=/usr/bin/dockerd -H unix:///var/run/docker.sock -H tcp://0.0.0.0:{{ node_docker_port }}"

- name: restart docker service
  systemd:
    name: docker.service
    state: restarted
