---
- name: install dependencies
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git

- name: clone contrail-dev-env repository
  git:
    repo: https://github.com/Juniper/contrail-dev-env.git
    dest: /home/centos/contrail-dev-env

- name: create contrail-dev-env containers
  shell: ./startup.sh
  args:
    chdir: /home/centos/contrail-dev-env

- name: prepare contrail-developer-sandbox container environment
  shell: docker exec contrail-developer-sandbox bash -c 'cd /root/contrail-dev-env && make sync && make fetch_packages && make setup && make dep'
