---

#- name: download archive
#  get_url:
#    url: "{{ archive }}"
#    dest: /tmp/data.tgz

- name: download archive
  shell: "aws s3 cp s3://tf-ci/{{archive}} /tmp/data.tgz"

- name: create dir for data
  file:
    path: /tmp/data
    state: directory

- name: unpack archive
  unarchive:
    src: /tmp/data.tgz
    remote_src: true
    dest: /tmp/data

- name: remove archive
  file:
    path: /tmp/data.tgz
    state: absent

# with_filetree looks good but we need relative paths
- name: upload data
  shell: "for f in $(find .); do curl -s -u {{ nexus_user }}:{{ nexus_password }} --upload-file $f http://{{ nexus_host }}/repository/${f} ; done"
  args:
    chdir: "/tmp/data"

- name: remove data
  file:
    path: /tmp/data
    state: absent
