---
- name: create gerrit etc directory
  file:
    path: /etc/gerrit/docker
    state: directory
    recurse: yes

- name: create gerrit lib directory
  file:
    path: /var/lib/gerrit
    state: directory
    recurse: yes

- name: set uid/gid for gerrit folder
  shell: "chown 1000:1000 /var/lib/gerrit"

- name: create gerrit db directory
  file:
    path: /var/lib/gerritdb
    state: directory
    recurse: yes

- name: collect gerrit oauth2 plugin
  get_url:
    url: https://github.com/davido/gerrit-oauth-provider/releases/download/v2.16.1/gerrit-oauth-provider.jar
    dest: /etc/gerrit/gerrit-oauth-provider.jar

- name: apply gerrit Dockerfile
  template:
    src: Dockerfile.j2
    dest: /etc/gerrit/gerrit-Dockerfile

- name: apply gerrit docker-compose.yaml
  template:
    src: docker-compose.yaml.j2
    dest: /etc/gerrit/docker-compose.yaml

- name: start gerrit service
  docker_service:
    project_src: /etc/gerrit
