---
- name: create gerrit etc directory
  file:
    path: /etc/gerrit/docker
    state: directory
    recurse: yes

- name: collect gerrit oauth2 plugin
  get_url:
    url: https://github.com/davido/gerrit-oauth-provider/releases/download/v2.16.1/gerrit-oauth-provider.jar
    dest: /etc/gerrit/docker/gerrit-oauth-provider.jar

- name: apply gerrit Dockerfile
  template:
    src: Dockerfile.j2
    dest: /etc/gerrit/docker/Dockerfile

- name: build gerrit docker image
  docker_image:
    path: /etc/gerrit/docker
    name: local/tf-ci-gerrit
    pull: no

- name: apply gerrit docker-compose.yaml
  template:
    src: docker-compose.yaml.j2
    dest: /etc/gerrit/docker-compose.yaml

- name: start gerrit service
  docker_service:
    project_src: /etc/gerrit
