---
- name: create gerrit etc directory
  file:
    path: /etc/gerrit/docker
    state: directory
    recurse: yes

- name: collect gerrit oauth2 plugin
  get_url:
    url: https://github.com/davido/gerrit-oauth-provider/releases/download/v2.16.1/gerrit-oauth-provider.jar
    dest: /etc/gerrit/gerrit-oauth-provider.jar

- name: apply gerrit Dockerfile
  template:
    src: Dockerfile.j2
    dest: /etc/gerrit/gerrit-Dockerfile

- name: apply gerrit docker-compose.yaml
  template:
    src: docker-compose.yaml.j2
    dest: /etc/gerrit/docker-compose.yaml

- name: start gerrit service
  docker_service:
    project_src: /etc/gerrit

- name: authenticate to gerrit
  include_role:
    name: gerrit-prepare-urllib

- name: check if zuul user exists
  uri:
    url: "http://{{ gerrit_host }}/accounts/zuul"
    status_code: 200, 404
    headers:
      Cookie: "{{ gerrit_cookies }}"
  register: zuul_user_check

- name: create zuul gerrit account
  uri:
    url: "http://{{ gerrit_host }}/accounts/zuul"
    method: PUT
    status_code: 201
    body_format: json
    body:
      name: zuul
      ssh_key: "{{ lookup('file', '{{ gerrit_ssh_keys }}/zuul_rsa.pub') }}"
      groups:
        - "Non-Interactive Users"
    headers:
      Cookie: "{{ gerrit_cookies }}"
      x-gerrit-auth: "{{ gerrit_auth }}"
  when:
    - zuul_user_check.status == 404 or (gerrit_force_create_zuul_user | default(false))

- name: add zuul SSH key to gerrit
  uri:
    url: "http://{{ gerrit_host }}/accounts/zuul/sshkeys"
    method: POST
    body: "{{ lookup('file', '{{ gerrit_ssh_keys }}/zuul_rsa.pub') }}"
    status_code: 201
    headers:
      Content-Type: text/plain
      Cookie: "{{ gerrit_cookies }}"
      x-gerrit-auth: "{{ gerrit_auth }}"
