---
- name: create gerrit etc directory
  file:
    path: /var/gerrit/etc
    state: directory
    owner: 1000
    group: 1000
    mode: '700'
    recurse: yes

- name: apply gerrit.config file
  template:
    src: gerrit.config.j2
    dest: /var/gerrit/etc/gerrit.config
    owner: 1000
    group: 1000
    mode: '700'

- name: apply secure.config file
  template:
    src: secure.config.j2
    dest: /var/gerrit/etc/secure.config
    owner: 1000
    group: 1000
    mode: '700'

- name: generate openssh RSA host key
  command : ssh-keygen -q -t rsa -f /var/gerrit/etc/ssh_host_rsa_key -C "" -N ""
  args:
    creates: /var/gerrit/etc/ssh_host_rsa_key

- name: fix owner of RSA host key
  file:
    path: /var/gerrit/etc/{{ item.src }}
    owner: 1000
    group: 1000
  with_items:
    - { src: "ssh_host_rsa_key" }
    - { src: "ssh_host_rsa_key.pub" }

- name: create gerrit etc directory
  file:
    path: /etc/gerrit
    state: directory

- name: apply gerrit docker-compose.yaml
  template:
    src: docker-compose.yaml.j2
    dest: /etc/gerrit/docker-compose.yaml

- name: start gerrit service
  docker_service:
    project_src: /etc/gerrit
