# Version 2 is the latest that is supported by docker-compose in
# Ubuntu Xenial.
version: '2'

services:
  zk:
    image: zookeeper
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zuul
      MYSQL_USER: zuul
      MYSQL_PASSWORD: secret
  scheduler:
    depends_on:
      - zk
      - mysql
    environment:
      no_proxy: "${no_proxy}"
    command: "zuul-scheduler -d"
#    command: "tail -f /dev/null"
    image: progmaticlab/zuul-scheduler:2.5.3
    ports:
      - "8001:8001"
    pid: host
    ipc: host
    volumes:
      - "./etc_zuul:/etc/zuul"
      - "./ssh_keys:/var/ssh"
      - "/var/log/zuul:/var/log/zuul"
      - "/var/run:/var/run"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  web:
    command: "zuul-web -d"
#    command: "sh -c 'pip3 install pymysql && zuul-web -d'"
#    command: "tail -f /dev/null"
    depends_on:
      - scheduler
      - mysql
    ports:
      - "9000:9000"
    image: progmaticlab/zuul-web:2.5.3
    pid: host
    ipc: host
    volumes:
      - "./etc_zuul:/etc/zuul"
      - "/var/log/zuul:/var/log/zuul"
      - "/var/run:/var/run"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  executor:
    privileged: true
    environment:
      no_proxy: "${no_proxy}"
#    command: "sh -c 'mkdir /var/log/zuul && zuul-executor -d'"
    command: "zuul-executor -d"
    ports:
      - "79:7900"
    depends_on:
      - scheduler
    image: progmaticlab/zuul-executor:2.5.3
    pid: host
    ipc: host
    volumes:
      - "./etc_zuul:/etc/zuul"
      - "./ssh_keys:/var/ssh"
      - "/root/.ssh:/root/.ssh"
      - "logs:/srv/static/logs:z"
      - "/var/log/zuul:/var/log/zuul"
      - "/var/lib/zuul:/var/lib/zuul"
      - "/var/run:/var/run"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  node:
    build:
      dockerfile: node-Dockerfile
      context: ./
      args:
        http_proxy: "${http_proxy}"
        https_proxy: "${http_proxy}"
        no_proxy: "${no_proxy}"
    volumes:
      - "./ssh_node:/root/.ssh"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  launcher:
    command: "nodepool-launcher -d"
    depends_on:
      - zk
    image: progmaticlab/nodepool-launcher:0.5.1
    pid: host
    ipc: host
    volumes:
      - "/var/log/zuul:/var/log/zuul"
      - "/var/run:/var/run"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "8022:8022"
  logs:
    build:
      dockerfile: logs-Dockerfile
      context: ./
      args:
        http_proxy: "${http_proxy}"
        https_proxy: "${http_proxy}"
        no_proxy: "${no_proxy}"
    ports:
      - "80:80"
    volumes:
      - "/var/www/logs:/usr/local/apache2/htdocs"
  front:
    build:
      dockerfile: front-Dockerfile
      context: ./
    depends_on:
      - scheduler
      - web
    ports:
      - "8080:8080"
    volumes:
      - "/var/log/zuul:/var/log/zuul"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

volumes:
  logs:
