---
- name: wait for gerrit service
  wait_for:
    host: "{{ gerrit_url | regex_replace('^(http|https)://(.*)$', '\\2') }}"
    port: 80

- name: create authentication cookie for later requests to gerrit
  uri:
    url: "{{ gerrit_url }}/login/?account_id=1000000"
    method: GET
    status_code: 302
    follow_redirects: false
  register: login

- name: store xsrf token for later requests to gerrit
  uri:
    url: "{{ gerrit_url }}/"
    method: GET
    headers:
      Cookie: "{{ login.set_cookie }}"
    status_code: 200
    follow_redirects: false
  register: xsrf

- name: create gerrit repositories
  include_role:
    name: gerrit-create-repo
  vars:
    source_namespace: "{{ item.src_namespace | default(item.dest_namespace) }}"
    target_namespace: "{{ item.dest_namespace }}"
    project_name: "{{ item.project }}"
    gerrit_user_cookie: "{{ login.set_cookie }}"
    xsrf_cookie: "{{ xsrf.set_cookie }}"
  with_items:
    - {dest_namespace: "Juniper", project: "contrail-ansible"}
    - {dest_namespace: "Juniper", project: "contrail-ansible-deployer"}
    - {dest_namespace: "Juniper", project: "contrail-ansible-internal"}
    - {dest_namespace: "Juniper", project: "contrail-api-client"}
    - {dest_namespace: "Juniper", project: "contrail-build"}
    - {dest_namespace: "Juniper", project: "contrail-common"}
    - {dest_namespace: "Juniper", project: "contrail-community-docs"}
    - {dest_namespace: "Juniper", project: "contrail-container-builder"}
    - {dest_namespace: "Juniper", project: "contrail-controller"}
    - {dest_namespace: "Juniper", project: "contrail-deployers-containers"}
    - {dest_namespace: "Juniper", project: "contrail-dev-env"}
    - {dest_namespace: "Juniper", project: "contrail-docker"}
    - {dest_namespace: "Juniper", project: "contrail-docs"}
    - {dest_namespace: "Juniper", project: "contrail-dpdk"}
    - {dest_namespace: "Juniper", project: "contrail-fabric-utils"}
    - {dest_namespace: "Juniper", project: "contrail-generateDS"}
    - {dest_namespace: "Juniper", project: "contrail-go-api"}
    - {dest_namespace: "Juniper", project: "contrail-heat"}
    - {dest_namespace: "Juniper", project: "contrail-helm-deployer"}
    - {dest_namespace: "Juniper", project: "contrail-horizon"}
    - {dest_namespace: "Juniper", project: "contrail-infra"}
    - {dest_namespace: "Juniper", project: "contrail-infra-doc"}
    - {dest_namespace: "Juniper", project: "contrail-java-api"}
    - {dest_namespace: "Juniper", project: "contrail-kolla-ansible", src_namespace: "progmaticlab"}
    - {dest_namespace: "Juniper", project: "contrail-neutron-plugin"}
    - {dest_namespace: "Juniper", project: "contrail-nova-vif-driver"}
    - {dest_namespace: "Juniper", project: "contrail-packages"}
    - {dest_namespace: "Juniper", project: "contrail-packaging"}
    - {dest_namespace: "Juniper", project: "contrail-project-config", src_namespace: "progmaticlab"}
    - {dest_namespace: "Juniper", project: "contrail-provisioning"}
    - {dest_namespace: "Juniper", project: "contrail-publisher"}
    - {dest_namespace: "Juniper", project: "contrail-puppet"}
    - {dest_namespace: "Juniper", project: "contrail-sandesh"}
    - {dest_namespace: "Juniper", project: "contrail-server-manager"}
    - {dest_namespace: "Juniper", project: "contrail-specs"}
    - {dest_namespace: "Juniper", project: "contrail-test"}
    - {dest_namespace: "Juniper", project: "contrail-test-ci"}
    - {dest_namespace: "Juniper", project: "contrail-third-party", src_namespace: "progmaticlab"}
    - {dest_namespace: "Juniper", project: "contrail-third-party-cache"}
    - {dest_namespace: "Juniper", project: "contrail-third-party-packages"}
    - {dest_namespace: "Juniper", project: "contrail-tripleo-heat-templates"}
    - {dest_namespace: "Juniper", project: "contrail-tripleo-puppet"}
    - {dest_namespace: "Juniper", project: "contrail-vcenter-manager"}
    - {dest_namespace: "Juniper", project: "contrail-vcenter-plugin"}
    - {dest_namespace: "Juniper", project: "contrail-vnc"}
    - {dest_namespace: "Juniper", project: "contrail-vro-plugin"}
    - {dest_namespace: "Juniper", project: "contrail-vrouter"}
    - {dest_namespace: "Juniper", project: "contrail-vrouter-java-api"}
    - {dest_namespace: "Juniper", project: "contrail-web-controller"}
    - {dest_namespace: "Juniper", project: "contrail-web-core"}
    - {dest_namespace: "Juniper", project: "contrail-web-server-manager"}
    - {dest_namespace: "Juniper", project: "contrail-web-storage"}
    - {dest_namespace: "Juniper", project: "contrail-webui-third-party"}
    - {dest_namespace: "Juniper", project: "contrail-windows"}
    - {dest_namespace: "Juniper", project: "contrail-windows-docker-driver"}
    - {dest_namespace: "Juniper", project: "contrail-zuul-jobs", src_namespace: "progmaticlab"}
    - {dest_namespace: "Juniper", project: "horizon"}
    - {dest_namespace: "Juniper", project: "nova"}
    - {dest_namespace: "Juniper", project: "openshift-ansible"}
    - {dest_namespace: "Juniper", project: "openstack-helm"}
    - {dest_namespace: "Juniper", project: "openstack-helm-infra"}
    - {dest_namespace: "Juniper", project: "puppet-contrail"}
    - {dest_namespace: "Juniper", project: "vijava"}
    - {dest_namespace: "Juniper", project: "zuul-jobs"}
    - {dest_namespace: "tungsten-infra", project: "ci-utils"}
    - {dest_namespace: "tungsten-infra", project: "containerregistry"}
    - {dest_namespace: "tungstenfabric-infra", project: "periodic-nightly"}
    - {dest_namespace: "tungstenfabric", project: "docs"}
    - {dest_namespace: "tungstenfabric", project: "tungsten-test-runner"}
