---
- name: authenticate to gerrit
  include_role:
    name: gerrit-prepare-urllib

- name: create gerrit repositories
  include: "create_repo.yaml repo_data={{ item }}"
  with_items: "{{ gerrit_repos }}"
