# Version 2 is the latest that is supported by docker-compose in
# Ubuntu Xenial.
version: '2'

services:
  zk:
    image: zookeeper
    ports:
      - "2181:2181"
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zuul
      MYSQL_USER: zuul
      MYSQL_PASSWORD: secret
  scheduler:
    depends_on:
      - zk
      - mysql
    environment:
      no_proxy: "${no_proxy}"
    command: "zuul-scheduler -d"
#    command: "tail -f /dev/null"
    image: progmaticlab/zuul-scheduler:2.5.3
    pid: host
    ipc: host
    ports:
      - "4730:4730"
    volumes:
      - "./etc_zuul:/etc/zuul"
      - "./ssh_keys:/var/ssh"
      - "./.ssh:/root/.ssh"
      - "/var/log/zuul:/var/log/zuul"
      - "/var/lib/zuul:/var/lib/zuul"
      - "/var/run:/var/run"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  web:
    command: "zuul-web -d"
#    command: "tail -f /dev/null"
    depends_on:
      - scheduler
      - mysql
    image: progmaticlab/zuul-web:2.5.3
    pid: host
    ipc: host
    volumes:
      - "./etc_zuul:/etc/zuul"
      - "/var/log/zuul:/var/log/zuul"
      - "/var/lib/zuul:/var/lib/zuul"
      - "/var/run:/var/run"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  logs:
    build:
      dockerfile: logs-Dockerfile
      context: ./
      args:
        http_proxy: "${http_proxy}"
        https_proxy: "${http_proxy}"
        no_proxy: "${no_proxy}"
    ports:
      - "{{ zuul_logs_port }}:80"
    volumes:
      - "/var/www/logs:/usr/local/apache2/htdocs"
  front:
    build:
      dockerfile: front-Dockerfile
      context: ./
    depends_on:
      - scheduler
      - web
    ports:
      - "{{ zuul_front_port }}:8080"
    volumes:
      - "/var/log/zuul:/var/log/zuul"
      - "/var/lib/zuul:/var/lib/zuul"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
