---

- name: collect hosts configuration
  include: collect-hosts.yaml

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0755
  with_items:
    - /var/log/zuul
    - /var/lib/zuul
    - /var/lib/zuul/builds
    - /var/lib/zuul/git
    - /var/lib/zuul/ssh
    - /var/lib/zuul/keys

- name: protect zuul keys folders
  file:
    path: "{{ item }}"
    mode: 0700
  with_items:
    - /var/lib/zuul/keys
