---
- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0777
  with_items:
    - /opt/nodepool-launcher/etc_nodepool
    - /var/log/zuul

- name: copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
  with_items:
    - {src: "./", dest: "/opt/nodepool-launcher"}

- name: apply nodepool configuration
  template:
    src: nodepool.yaml.j2
    dest: /opt/nodepool-launcher/etc_nodepool/nodepool.yaml

- name: start nodepool-launcher service
  docker_service:
    project_src: /opt/nodepool-launcher/
