---
- name: check if gerrit_ssh_keys variable is set
  fail:
    msg: gerrit_ssh_keys is not defined
  when: gerrit_ssh_keys is not defined

- name: "create {{ gerrit_ssh_keys }} directory"
  file:
    path: "{{ gerrit_ssh_keys }}"
    state: directory
    recurse: yes

- name: generate ssh keys
  include: "generate_key.yaml key_name={{ item }}"
  with_items:
    - zuul
    - nodepool
    - logserver
