---
- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0777
  with_items:
    - /opt/zuul-web/etc_zuul

- name: copy zuul config files
  copy:
    src: "./"
    dest: "/opt/zuul-web"
    force: true

- name: apply zuul configuration
  template:
    src: zuul.conf.j2
    dest: /opt/zuul-web/etc_zuul/zuul.conf

- name: apply nginx configuration
  template:
    src: zuul.nginx.conf.j2
    dest: /opt/zuul-web/zuul.nginx.conf

- name: start zuul-web service
  docker_service:
    project_src: /opt/zuul-web/
