---

- name: build containers
  include_role:
    name: build
    tasks_from: zuul
  vars:
    - component: web
  when: zuul_build_containers

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0755
  with_items:
    - /opt/zuul-web/etc_zuul

- name: copy zuul config files
  copy:
    src: "./"
    dest: "/opt/zuul-web"
    force: true
    mode: 0644

- name: apply zuul configuration
  template:
    src: zuul.conf.j2
    dest: /opt/zuul-web/etc_zuul/zuul.conf
    mode: 0644

- name: apply docker-compose configuration
  template:
    src: docker-compose.yaml.j2
    dest: /opt/zuul-web/docker-compose.yaml
    mode: 0644

- name: apply nginx configuration
  template:
    src: zuul.nginx.conf.j2
    dest: /opt/zuul-web/zuul.nginx.conf
    mode: 0644

- name: start zuul-web service
  docker_service:
    project_src: /opt/zuul-web/
