---

- name: build containers
  include_role:
    name: build
    tasks_from: zuul
  vars:
    - component: web
  when: zuul_build_containers

- name: detect if built container exists (check for latest tag)
  when: not zuul_build_containers
  block:
    - command: "docker image inspect {{ ZUUL_DOCKERREPO }}/zuul-web:latest"
      register: di_check_res
      no_log: true
    - set_fact:
        ZUUL_VERSION: latest
      when: di_check_res is success

- name: create configuration
  include_role:
    name: zuul-conf

- name: apply docker-compose configuration
  template:
    src: docker-compose.yaml.j2
    dest: /opt/zuul-web/docker-compose.yaml
    mode: 0600

- name: apply nginx configuration
  template:
    src: zuul.nginx.conf.j2
    dest: /opt/zuul-web/zuul.nginx.conf
    mode: 0600

- name: start zuul-web service
  docker_service:
    project_src: /opt/zuul-web/
