---

- name: build containers
  include_role:
    name: build
    tasks_from: zuul
  vars:
    - component: scheduler
  when: zuul_build_containers

- name: init DB
  include_role:
    name: zuul-initdb

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0755
    owner: zuul
    group: zuul
  with_items:
    - /opt/zuul-scheduler/.ssh

- name: copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    mode: 0644
    owner: zuul
    group: zuul
  with_items:
    - {src: "./", dest: "/opt/zuul-scheduler"}
    - {src: "{{ gerrit_ssh_keys }}/zuul_rsa", dest: "/opt/zuul-scheduler/ssh_keys/"}

- name: protect SSH private keys
  file:
    path: /opt/zuul-scheduler/ssh_keys/{{ item }}_rsa
    mode: 0600
    owner: zuul
    group: zuul
  with_items:
    - zuul

- name: construct known_hosts for gerrit
  shell: "ssh-keyscan -p {{ item.port }} -t ecdsa {{ item.host }} >> /opt/zuul-scheduler/.ssh/known_hosts"
  with_items:
    - {host: "{{ gerrit_host }}", port: 22}
    - {host: "{{ gerrit_host }}", port: 29418}

# TODO remove after debugging mirroring  
# - name: construct known_hosts for review.opencontrail.org
#   shell: "ssh-keyscan -p {{ item.port }} >> /opt/zuul-scheduler/.ssh/known_hosts"
#     - {host: "review.opencontrail.org", port: 22}
#     - {host: "review.opencontrail.org", port: 29418}

- name: protect SSH private keys
  file:
    path: /opt/zuul-scheduler/.ssh/known_hosts
    owner: zuul
    group: zuul

- name: apply zuul configuration
  template:
    src: zuul.conf.j2
    dest: /opt/zuul-scheduler/etc_zuul/zuul.conf
    mode: 0644
    owner: zuul
    group: zuul

- name: apply zuul compose file
  template:
    src: docker-compose.yaml.j2
    dest: /opt/zuul-scheduler/docker-compose.yaml
    mode: 0644

- name: start zuul-scheduler service
  docker_service:
    project_src: /opt/zuul-scheduler/
