---
- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0755
  with_items:
    - /opt/zuul-scheduler/.ssh
    - /var/log/zuul
    - /var/lib/zuul/build
    - /var/lib/zuul/git
    - /var/lib/zuul/ssh

# for now log server is placed in scheduler and accessed from executor with ubuntu user
- name: create logs directory
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    recurse: yes
    mode: 0755
  with_items:
    - /var/www/logs

- name: copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
  with_items:
    - {src: "./", dest: "/opt/zuul-scheduler"}
    - {src: "{{ gerrit_ssh_keys }}/", dest: "/opt/zuul-scheduler/ssh_keys"}

- name: protect SSH private keys
  file:
    path: /opt/zuul-scheduler/ssh_keys/{{ item }}_rsa
    mode: 0600
  with_items:
    - admin
    - zuul
    - nodepool

- name: construct authorized_keys for zuul
  shell: "cat /opt/zuul-scheduler/ssh_keys/{{ item }}_rsa.pub >> /opt/zuul-scheduler/.ssh/authorized_keys"
  with_items:
    - nodepool

- name: construct known_hosts for gerrit
  shell: "ssh-keyscan -p {{ item.port }} -t ecdsa {{ item.host }} >> /opt/zuul-scheduler/.ssh/known_hosts"
  with_items:
    - {host: "{{ gerrit_host }}", port: 22}
    - {host: "{{ gerrit_host }}", port: 29418}

- name: apply zuul configuration
  template:
    src: zuul.conf.j2
    dest: /opt/zuul-scheduler/etc_zuul/zuul.conf

- name: apply zuul compose file
  template:
    src: docker-compose.yaml.j2
    dest: /opt/zuul-scheduler/docker-compose.yaml

- name: start zuul-scheduler service
  docker_service:
    project_src: /opt/zuul-scheduler/
