---

- name: build containers
  include_role:
    name: build
    tasks_from: zuul
  vars:
    - component: executor
  when: zuul_build_containers

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0755
    owner: zuul
    group: zuul
  with_items:
    - /opt/zuul-executor/.ssh
    - /opt/zuul-executor/etc_zuul

- name: copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    mode: 0644
    owner: zuul
    group: zuul
  with_items:
    - {src: "./", dest: "/opt/zuul-executor"}
    - {src: "{{ gerrit_ssh_keys }}/zuul_rsa", dest: "/opt/zuul-executor/ssh_keys/"}
    - {src: "{{ gerrit_ssh_keys }}/nodepool_rsa", dest: "/opt/zuul-executor/ssh_keys/"}

- name: protect SSH private keys
  file:
    path: /opt/zuul-executor/ssh_keys/{{ item }}_rsa
    mode: 0600
    owner: zuul
    group: zuul
  with_items:
    - zuul
    - nodepool

- name: construct known_hosts for gerrit
  shell: "ssh-keyscan -p {{ item.port }} -t ecdsa {{ item.host }} >> /opt/zuul-executor/.ssh/known_hosts"
  with_items:
    - {host: "{{ gerrit_host }}", port: 22}
    - {host: "{{ gerrit_host }}", port: 29418}

# TODO remove after debugging mirroring  
- name: construct known_hosts for review.opencontrail.org
  shell: "ssh-keyscan -p {{ item.port }} -t ecdsa {{ item.host }} >> /opt/zuul-executor/.ssh/known_hosts"
    - {host: "review.opencontrail.org", port: 22}
    - {host: "review.opencontrail.org", port: 29418}

- name: protect SSH private keys
  file:
    path: /opt/zuul-executor/.ssh/known_hosts
    owner: zuul
    group: zuul

- name: apply zuul configuration
  template:
    src: zuul.conf.j2
    dest: /opt/zuul-executor/etc_zuul/zuul.conf
    mode: 0644
    owner: zuul
    group: zuul

- name: apply site-variables template
  template:
    src: site-variables.yaml.j2
    dest: /opt/zuul-executor/etc_zuul/site-variables.yaml
    mode: 0644
    owner: zuul
    group: zuul

- name: apply docker-compose configuration
  template:
    src: docker-compose.yaml.j2
    dest: /opt/zuul-executor/docker-compose.yaml
    mode: 0644

- name: start zuul-executor service
  docker_service:
    project_src: /opt/zuul-executor/
    restarted: true
