- tenant:
    name: opencontrail
    max-job-timeout: -1
    source:
      github:
        config-projects:
          - progmaticlab/contrail-project-config
        untrusted-projects:
          - progmaticlab/contrail-zuul-jobs:
              shadow: progmaticlab/contrail-project-config
          - Juniper/zuul-jobs:
              shadow: progmaticlab/contrail-project-config
          - tungstenfabric/zuul:
              exclude:  ['pipeline', 'job', 'semaphore', 'project', 'secret', 'project-template', 'nodeset']
          - Juniper/contrail-publisher
          - tungsten-infra/ci-utils
          - tungsten-infra/containerregistry
          - tungstenfabric/tf-dev-env
      gerrit:
        untrusted-projects:
          - Juniper/contrail
          - Juniper/contrail-analytics
          - Juniper/contrail-ansible-deployer
          - Juniper/contrail-api-client
          - Juniper/contrail-build
          - Juniper/contrail-common
          - Juniper/contrail-community-docs
          - Juniper/contrail-container-builder
          - Juniper/contrail-controller
          - Juniper/contrail-deployers-containers
          - Juniper/contrail-docs
          - Juniper/contrail-dpdk
          - Juniper/contrail-fabric-utils
          - Juniper/contrail-generateDS
          - Juniper/contrail-go-api
          - Juniper/contrail-heat
          - Juniper/contrail-helm-deployer
          - Juniper/contrail-horizon
          - Juniper/contrail-infra
          - Juniper/contrail-infra-doc
          - Juniper/contrail-java-api
          - Juniper/contrail-kolla-ansible:
              exclude:  ['pipeline', 'job', 'semaphore', 'project', 'secret', 'project-template', 'nodeset']
          - Juniper/contrail-neutron-plugin
          - Juniper/contrail-nova-vif-driver
          - Juniper/contrail-packages
          - Juniper/contrail-packaging
          - Juniper/contrail-provisioning
          - Juniper/contrail-sandesh
          - Juniper/contrail-specs
          - Juniper/contrail-test
          - Juniper/contrail-test-ci
          - Juniper/contrail-third-party
          - Juniper/contrail-third-party-packages
          - Juniper/contrail-tripleo-heat-templates
          - Juniper/contrail-tripleo-puppet
          - Juniper/contrail-vro-plugin
          - Juniper/contrail-vrouter
          - Juniper/contrail-vrouter-java-api
          - Juniper/contrail-webui-third-party
          - Juniper/contrail-web-controller
          - Juniper/contrail-web-core
          - Juniper/contrail-windows
          - Juniper/contrail-windows-docker-driver
          - Juniper/contrail-windows-test
          - Juniper/contrail-vcenter-fabric-manager
          - Juniper/contrail-vcenter-manager
          - Juniper/contrail-vcenter-plugin
          - Juniper/contrail-vnc
          - Juniper/openshift-ansible
          - Juniper/openstack-helm:
              exclude:  ['pipeline', 'job', 'semaphore', 'project', 'secret', 'project-template', 'nodeset']
          - Juniper/openstack-helm-infra:
              exclude:  ['pipeline', 'job', 'semaphore', 'project', 'secret', 'project-template', 'nodeset']
          - Juniper/puppet-contrail
          - Juniper/vijava
          - tungstenfabric/docs
          - tungstenfabric/tungsten-test-runner
          # migrated section
          - tungstenfabric/analytics
