---
- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0755
  with_items:
    - /opt/nodepool-builder/etc_nodepool
    - /opt/nodepool-builder/.ssh
    - /opt/nodepool/images
    - /var/log/zuul

- name: copy ssh keys
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    mode: 0644
  with_items:
    - {src: "{{ gerrit_ssh_keys }}/zuul_rsa", dest: "/opt/nodepool-builder/ssh_keys/"}
    - {src: "{{ gerrit_ssh_keys }}/nodepool_rsa.pub", dest: "/opt/nodepool-builder/ssh_keys/"}

- name: protect SSH private keys
  file:
    path: /opt/nodepool-builder/ssh_keys/{{ item }}_rsa
    mode: 0600
  with_items:
    - zuul

- name: remove config derectory
  file:
    path: /opt/nodepool-builder/config
    state: absent

- name: "clone {{ zuul_config_project }}"
  git:
    repo: "ssh://zuul@{{ gerrit_host }}:29418/{{ zuul_config_project }}"
    dest: /opt/nodepool-builder/config
    accept_hostkey: yes
    force: true
    key_file: /opt/nodepool-builder/ssh_keys/zuul_rsa

- name: copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    mode: 0644
  with_items:
    - {src: "./", dest: "/opt/nodepool-builder"}

- name: start nodepool-builder service
  docker_service:
    project_src: /opt/nodepool-builder/
    restarted: true
