---
- name: create nexus etc directory
  file:
    path: /etc/nexus
    state: directory

- name: apply docker-compose.yaml
  template:
    src: docker-compose.yaml.j2
    dest: /etc/nexus/docker-compose.yaml

- name: start nexus service
  docker_service:
    project_src: /etc/nexus
