---
- name: check if key {{ key_name }} exists
  stat:
    path: "{{ gerrit_ssh_keys }}/{{ key_name }}_rsa"
  register: stat_result
  delegate_to: localhost
  become: no

- name: remove existing key {{ key_name }}
  file:
    path: "{{ key_path }}"
    state: absent
  with_items:
    - "{{ gerrit_ssh_keys }}/{{ key_name }}_rsa"
    - "{{ gerrit_ssh_keys }}/{{ key_name }}_rsa.pub"
  loop_control:
        loop_var: key_path
  when:
    - stat_result.stat.exists
    - gerrit_force_ssh_keys_generate | default(false)

- name: generate SSH key {{ key_name }}_rsa for gerrit
  command: "ssh-keygen -m pem -f {{ gerrit_ssh_keys }}/{{ key_name }}_rsa -N '' -q"
  delegate_to: localhost
  become: no
  when: not stat_result.stat.exists or (gerrit_force_ssh_keys_generate | default(false))
