---
- hosts: nexus
  remote_user: "{{ remote_user }}"
  become: yes
  roles:
    - python
    - docker
    - nexus
  pre_tasks:
  - name: install python for ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)