---
- hosts: zuul*
  remote_user: "{{ remote_user }}"
  become: yes
  gather_facts: no
  roles:
    - python
  pre_tasks:
  - name: install python for ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: zuul*
  remote_user: "{{ remote_user }}"
  become: yes
  gather_facts: yes
  roles:
    - ntp
    - common
    - docker
    - zuul-prepare

- hosts: zuul-scheduler
  remote_user: "{{ remote_user }}"
  become: yes
  gather_facts: yes
  roles:
    - zuul-scheduler

- hosts: zuul-executor
  remote_user: "{{ remote_user }}"
  become: yes
  gather_facts: yes
  roles:
    - zuul-executor

- hosts: zuul-web
  remote_user: "{{ remote_user }}"
  become: yes
  gather_facts: yes
  roles:
    - zuul-web
