---
- hosts: zuul-scheduler
  remote_user: "{{ remote_user }}"
  become: yes
  roles:
    - python
    - docker
    - zuul-hosts
    - zuul-scheduler

- hosts: zuul-executor
  remote_user: "{{ remote_user }}"
  become: yes
  roles:
    - python
    - docker
    - zuul-hosts
    - zuul-executor

- hosts: nodepool-launcher
  remote_user: "{{ remote_user }}"
  become: yes
  roles:
    - python
    - docker
    - zuul-hosts
    - nodepool-launcher